import { useState } from 'react';
import { Badge, Card } from '../../components/ui';
import { formatDateTime, safeParseJSON, STATUS_TONE, URGENCY_TONE } from '../../utils/format';
import PostVisitForm from './PostVisitForm';

function QueueItem({ appointment, onChanged }) {
  const [showForm, setShowForm] = useState(false);
  const preVisit = safeParseJSON(appointment.aiPreVisitSummary);
  const postVisit = safeParseJSON(appointment.aiPostVisitSummary);
  const canDocument = ['PENDING', 'CONFIRMED'].includes(appointment.status);

  return (
    <div className="rounded-md border border-slate-200 p-4">
      <div className="flex items-start justify-between">
        <div>
          <p className="font-medium text-slate-900">{appointment.patient.name}</p>
          <p className="text-sm text-slate-500">{appointment.patient.email}</p>
          <p className="mt-1 text-sm text-slate-700">{formatDateTime(appointment.scheduledAt)}</p>
        </div>
        <Badge tone={STATUS_TONE[appointment.status]}>{appointment.status}</Badge>
      </div>

      {appointment.symptoms && (
        <p className="mt-2 text-sm text-slate-600">
          <span className="font-medium">Symptoms:</span> {appointment.symptoms}
        </p>
      )}

      {appointment.aiPreVisitSummary && preVisit ? (
        <div className="mt-3 rounded-md bg-slate-50 p-3 text-sm">
          <div className="mb-1 flex items-center gap-2">
            <span className="font-medium text-slate-700">AI urgency assessment</span>
            <Badge tone={URGENCY_TONE[appointment.triageLevel] || 'slate'}>{appointment.triageLevel}</Badge>
          </div>
          <p className="text-slate-600">{preVisit.chiefComplaint}</p>
          {preVisit.suggestedQuestions?.length > 0 && (
            <div className="mt-1">
              <p className="text-xs font-medium text-slate-500">Suggested questions:</p>
              <ul className="list-inside list-disc text-slate-500">
                {preVisit.suggestedQuestions.map((q, i) => (
                  <li key={i}>{q}</li>
                ))}
              </ul>
            </div>
          )}
        </div>
      ) : (
        <p className="mt-2 text-xs text-slate-400">No AI pre-visit summary generated by the patient yet.</p>
      )}

      {appointment.status === 'COMPLETED' &&
        (appointment.aiPostVisitSummary && postVisit ? (
          <div className="mt-3 rounded-md bg-green-50 p-3 text-sm">
            <p className="mb-1 font-medium text-green-800">Post-visit summary submitted</p>
            <p className="text-green-700">{postVisit.patientSummary}</p>
            {appointment.followUpDate && (
              <p className="mt-1 text-xs text-green-600">Follow up by {formatDateTime(appointment.followUpDate)}</p>
            )}
          </div>
        ) : (
          <p className="mt-2 text-xs text-slate-400">No AI post-visit summary available.</p>
        ))}

      {canDocument && !postVisit && (
        <>
          {!showForm ? (
            <button
              className="mt-3 text-sm font-medium text-blue-600 hover:underline"
              onClick={() => setShowForm(true)}
            >
              Add clinical notes
            </button>
          ) : (
            <PostVisitForm appointment={appointment} onSubmitted={() => { setShowForm(false); onChanged(); }} />
          )}
        </>
      )}
    </div>
  );
}

export default function DoctorQueue({ appointments, onChanged }) {
  return (
    <Card>
      <h2 className="mb-4 text-base font-semibold text-slate-900">Appointment queue ({appointments.length})</h2>
      {appointments.length === 0 ? (
        <p className="text-sm text-slate-500">No appointments scheduled for this day.</p>
      ) : (
        <div className="space-y-3">
          {appointments.map((appt) => (
            <QueueItem key={appt.id} appointment={appt} onChanged={onChanged} />
          ))}
        </div>
      )}
    </Card>
  );
}
